# Site settings
title: Spatial R
email: ekt.batey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A project repository for working with spatial data and maps in R
baseurl: "/spatial" # the subpath of your site, e.g. /blog/
url: "http://tbatey.org" # the base hostname & protocol for your site
twitter_username: bateytk
github_username:  bateyt

# Build settings
markdown: kramdown

# Syntax highlighting
highligher: pygments
